module.exports.userController =require('./user.controller');
module.exports.messageController = require('./message.controller');
module.exports.pushNotificationController = require('./pushNotification.controller');
module.exports.tokenController = require('./token.controller');
module.exports.transactionController = require('./transaction.controller');
module.exports.testController = require('./test.controller');
module.exports.notificationController = require('./notification.controller');
module.exports.priceController = require('./price.controller');
module.exports.candlestickController = require('./candlestick.controller');